kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

workspace:
  path: /drone/src

steps:


  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world