###

# curl 'https://www.payub8demo.com/ajax/order'
#  -H 'authority: www.payub8demo.com'
#  -H 'sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"'
#  -H 'accept: application/json'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'sec-fetch-site: same-origin'
#  -H 'sec-fetch-mode: cors'
#  -H 'sec-fetch-dest: empty'
#  -H 'referer: https://www.payub8demo.com/withdraw/withdrawList'
#  -H 'accept-language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6'
#  -H 'cookie: SessionId=e4644647-474a-47c1-a5b5-4f2d74c55f27'
#  --compressed
GET https://www.payub8demo.com/ajax/order
authority: www.payub8demo.com
sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
accept: application/json
sec-ch-ua-mobile: ?0
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
sec-ch-ua-platform: "Windows"
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
referer: https://www.payub8demo.com/withdraw/withdrawList
accept-language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6
cookie: SessionId=e4644647-474a-47c1-a5b5-4f2d74c55f27

###

