apiVersion: v1
kind: Namespace
metadata:
  name: devops


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    creator: admin
  creationTimestamp: "2019-11-21T07:55:50Z"
  name: jenkins
  namespace: devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: jenkins
      name: jenkins
      namespace: devops
    spec:
      containers:
      - image: jenkins/jenkins:lts-alpine
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        name: jenkins
        volumeMounts:
        - name: jenkins-volume
          mountPath: /var/jenkins_home
        - name: jenkins-localtime
          mountPath: /etc/localtime
        env:
          - name: JAVA_OPTS
            value: '-Xms256m -Xmx1024m -Duser.timezone=Asia/Shanghai'
          - name: TRY_UPGRADE_IF_NO_MARKER
            value: 'true'
        ports:
        - name: http
          containerPort: 8080
        - name: agent
          containerPort: 50000
        resources:
          requests:
            cpu: 200m
            memory: 500M
          limits:
            cpu: 800m
            memory: 1.5Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: jenkins-admin
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: jenkins-localtime
          hostPath:
            path: /etc/localtime
        - name: jenkins-volume
          hostPath:
            path: /data/jenkins_home
