version: "3"
services:
  redis-1:
    image: redis
    ports:
    - 6379
  redis-2:
    image: redis
    ports:
    - 6379
  envoy:
    image: envoyproxy/envoy-alpine:v1.15-latest
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml"]
    volumes:
    - ./envoy.yaml:/etc/envoy.yaml
    ports:
    - 1999:1999
    - 8001:8001
