/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practise.workspace.app;

public class App {
    public static void main(String[] args) {
        System.out.println(System.nanoTime());
    }
}
