apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dp
spec:
  replicas: 1
  minReadySeconds: 10 #表示Port起來要等10秒 有延遲方便查看效果
  selector:
    matchLabels:
      app: mysql-dp #標籤要和template label裡面一樣
  template:
    metadata:
      labels:
        app: mysql-dp
    spec:
      containers:
        - name: mysql-dp
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: k8sDb
            - name: MYSQL_USER
              value: tommy
            - name: MYSQL_PASSWORD
              value: tommy


          volumeMounts:
            - name: mysql-persistent-volume #要與volumes 裡面name一樣
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' identified by 'root' with grant option;;
    GRANT ALL PRIVILEGES ON *.* TO 'tommy'@'%' identified by 'tommy' with grant option;;
    FLUSH PRIVILEGES;