version: '3'
services:
  jenkins-docker:
    container_name: jenkins-docker
    build: .
    ports:
      - "51100:8080"
      - "51101:50000"
    privileged: true
    user: root
    volumes:
      - ./data:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

### /var/jenkins_home/secrets/initialAdminPassword
### sudo chmod 777 /var/run/docker.sock
### docker exec jenkins-docker docker ps
