apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deployment-service
  name: nginx-deployment-service
spec:
  selector: # LABELS
    app: my-nginx # app=my-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP

# [root@master k8s]# kubectl get pod --show-labels
# NAME                                READY   STATUS    RESTARTS   AGE   LABELS
# nginx-deployment-8475f9f6cc-755tf   1/1     Running   0          32m   app=my-nginx,pod-template-hash=8475f9f6cc
# nginx-deployment-8475f9f6cc-br9zs   1/1     Running   0          28m   app=my-nginx,pod-template-hash=8475f9f6cc
# nginx-deployment-8475f9f6cc-d468t   1/1     Running   0          32m   app=my-nginx,pod-template-hash=8475f9f6cc