version: '3'
services:

  fluentd:
    container_name: file-fluent-bit-server
    image: fluent/fluent-bit
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs
      - ./conf:/fluent-bit/etc
      - ./input:/fluentd/log/files/ #Example: Reading logs from a file
      - ./output:/output/ # Example: Fluentd will collect logs and store it here for demo
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"

  # This app writes logs to a local file
  file-myapp:
    container_name: file-fluent-bit-input
    image: alpine:3.16.2
    volumes:
      - ./input:/app
    command: [ /bin/sh , -c , "chmod +x /app/app.sh && ./app/app.sh" ]