version: '3'
services:

  fluentd:
    image: fluent/fluent-bit
    volumes:
      - ./conf:/fluent-bit/etc
    ports:
      - "9880:9880"
    hostname: fluentd
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"

  # This app writes logs to a local file
  file-myapp:
    container_name: file-fluentd-input
    image: alpine:3.16.2
    volumes:
      - ./input:/app
    command: [ /bin/sh , -c , "chmod +x /app/app.sh && ./app/app.sh" ]