version: "3"
services:


  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentd
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs
      - ./input:/fluentd/log/files/ #Example: Reading logs from a file
      - ./conf:/fluentd/etc/
      - ./output:/output/ # Example: Fluentd will collect logs and store it here for demo
    logging:
      driver: "local"


  # This app writes logs to a local file
  file-myapp:
    container_name: file-myapp
    image: alpine
    volumes:
      - ./input:/app
    command: [ /bin/sh , -c , "chmod +x /app/app.sh && /app/app.sh" ]
