# https://itnext.io/kubernetes-what-are-endpoints-3cc9e769b614
kind: Service
apiVersion: v1
metadata:
  name: external-svc
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-svc
subsets:
  - addresses:
      - ip: 139.59.205.180
    ports:
      - port: 80
        name: web
# name: must be the same as the Service
# ports.port and ports.name also must be the same as the corresponding Service

#  kubectl port-forward external-svc 8000:80