version: "3"
services:
  weblogic12c:
    image: store/oracle/weblogic:12.2.1.4-dev-200117
    ports:
      - "8080:7001"
      - "9002:9002"
    volumes:
      - ./domain.properties:/u01/oracle/properties/domain.properties
      - ./data:/tmp/war
    restart: always
    environment:
      #      - ADMIN_PASSWORD=tommy
      - DOMAIN_NAME=docker_domain
      - ADMINISTRATION_PORT_ENABLED=false