version: "3"
services:
  db:
    container_name: mysql_init_sql
    build: .
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql