#   http://localhost:3000/login/oauth/authorize?client_id=38c38b5e-29a3-477b-97ae-86c5459f291b&redirect_uri=http://localhost/login&response_type=code&state=365a858149c6e2d1
GET http://localhost:3000/login/oauth/authorize?client_id=38c38b5e-29a3-477b-97ae-86c5459f291b&redirect_uri=http%3A%2F%2Flocalhost%2Flogin&response_type=code&state=365a858149c6e2d1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Language: zh-TW,zh;q=0.9
Connection: keep-alive
Cookie: i_like_gitea=c43e6a06e48eab54; lang=zh-TW; _csrf=bzO-DZ2bJh3cJ4hVEZyWp-5rtuU6MTY2ODMwOTI2MjcxOTQxNDQwMA; _oauth_state_=365a858149c6e2d1
Referer: http://localhost:8080/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-site
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###


###