version: "3.9"
services:

  tomcat9:
    container_name: yudady-tomcat
    image: tomcat:9.0.62-jre17-temurin-focal
    ports:
      - 8080:8080
    volumes:
      - ./conf/webapps:/usr/local/tomcat/webapps:ro

