version: "3"
services:


  fluentd:
    container_name: http-fluentd-server
    image: fluentd:v1.14-1
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs
      - ./conf:/fluentd/etc/
      - ./input:/fluentd/log/files/ #Example: Reading logs from a file
      - ./output:/output/ # Example: Fluentd will collect logs and store it here for demo
    logging:
      driver: "local"


  # This app writes logs to a local file
  http-myapp:
    container_name: http-fluentd-app
    image: alpine
    volumes:
      - ./input:/app
    command: [ /bin/sh , -c , "apk add --no-cache curl && chmod +x /app/app.sh && /app/app.sh" ]
