version: "3.9"
services:
  nginx:
    container_name: yudady-nginx
    image: nginx:1.21.6
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx/static-html-directory:/usr/share/nginx/html:ro
      - ./conf/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx/

  tomcat01:
    container_name: yudady-tomcat01
    image: tomcat:9.0.62-jre17-temurin-focal
#    ports:
#      - 8081:8080
    volumes:
      - ./conf/tomcat01/webapps:/usr/local/tomcat/webapps:ro

  tomcat02:
    container_name: yudady-tomcat02
    image: tomcat:9.0.62-jre17-temurin-focal
#    ports:
#      - 8082:8080
    volumes:
      - ./conf/tomcat02/webapps:/usr/local/tomcat/webapps:ro

