version: '3'
services:
  dns:
    build: .
    hostname: ns
    network_mode: host
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./conf/named.conf:/etc/bind/named.conf:z
      - ./conf/zone/:/etc/bind/zone/:z
    command: named -c /etc/bind/named.conf -g -u named