# This is a basic workflow to help you get started with Actions

name: kustomization-tag

env:
  REPO_OWNER: yudady
  REPO_NAME: example-event-dispatcher-workflows
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [kustomization-tag]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kustomization-tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
        if: ${{ github.event.client_payload.image }}


      - name: kustomize edit
        run: |
          pwd
          ls
          cd argocd-app-config/dev/k8s
          pwd
          ls
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          kustomize edit set image ${{ github.event.client_payload.image }}:${{ github.event.client_payload.sha-tag }}
          rm -f kustomize
          cat kustomization.yaml
          cd ../../../
          
      - name: push
        uses: actions-x/commit@v6


#POST https://api.github.com/repos/yudady/example-event-dispatcher-workflows/dispatches
#Accept: application/vnd.github+json
#Authorization: Bearer xxxxxxxxxxxxxxxxxxx
#Content-Type: application/x-www-form-urlencoded
#
#  {
#    "event_type": "kustomization-tag",
#    "client_payload": {
#      "image": "364950776/flask-demo",
#      "sha-tag": "v5"
#    }
#  }