version: "3"
services:
  vsftpd:
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./data:/home/vsftpd
    restart: always
    environment:
      - FTP_USER=FQ6.UB8
      - FTP_PASS=AB7UaPUkx0
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
