apiVersion: v1
kind: Pod
metadata:
  name: probe-tcp
spec:
  containers:
    - name: nginx
      image: busybox:1.33.1
      livenessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 1
        tcpSocket:
          port: 80
