version: '3.7'
services:
  redis:
    image: redis:6.0.0
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./data/redis:/data
      - ./conf:/etc/redis
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always

