apiVersion: v1
kind: Pod
metadata:
  name: probe-tcp
spec:
  containers:
    - name: nginx
      image: yudady/myapp:v1
      livenessProbe:
        initialDelaySeconds: 5
        tcpSocket:
          port: 8080
        timeoutSeconds: 1
        periodSeconds: 3
