version: '3.9'

services:
  gitea-server:
    container_name: gitea
    image: gitea/gitea:latest # 直接装最新版就好了，没啥好选的，随意
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - web
    volumes:
      - ./data:/data  # /home/data可以替换成你想要的挂载目录
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000" # 外网33000对应内部容器3000端口
      - "22:22" # 外网33333对应内部容器22端口

######################################################

  drone-server:
    restart: always
    image: drone/drone:2
    ports:
      - "80:80"
    volumes:
      - ./data/drone-server/drone:/var/lib/drone/
      - ./data/drone-server/data:/data/
    environment:
      - DRONE_GITEA_SERVER=http://xxxxxxxxx:3000/ # Gitea访问地址
      - DRONE_GITEA_CLIENT_ID=xxxxxxxxx # 应用ID,下一步会获取
      - DRONE_GITEA_CLIENT_SECRET=xxxxxxxxx # 应用密钥,下一步会获取
      - DRONE_SERVER_HOST=xxxxxxxxx:9999
      - DRONE_SERVER_PROTO=http # 支持http, https
      - DRONE_RPC_SECRET=xxxxxxxxx # 通信密钥,下一步会获取
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GIT_USERNAME=xxxxxxxxx # git用户名
      - DRONE_GIT_PASSWORD=xxxxxxxxx # git密码
      - DRONE_USER_CREATE=username:xxxxxxxxx,admin:true # 管理员用户名,开启管理员账户



  drone-runner-docker:
    image: drone/drone-runner-docker:1
    ports:
      - "10000:3000"
    restart: always
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http # 支持http, https
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=xxxxxxxxx # 通信密钥,下一步会获取
      - DRONE_RUNNER_NAME=drone-runner-docker
      - DRONE_RUNNER_CAPACITY=2

######################################################

networks:
  web:
    external: true

