version: '3.9'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --api=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.console.address=:8080
      - --certificatesresolvers.letsencrypt.acme.email=yudady@email.com  # replace with your email
      - --certificatesresolvers.letsencrypt.acme.storage=acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entrypoint.permanent=true
#      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory # IMPORTANT Please delate current Let's Encrypt certificates so new ones can be obtained from production server
      - --log.level=DEBUG
      - --log.filePath=/logs/traefik.log
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/acme:/acme
      - ./data/traefik/logs:/logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.thisproxylocal.rule=Host(`192.168.100.120`) # Change 192.168.100.120 to your Docker server IP.
      - traefik.http.routers.thisproxylocal.entryPoints=console,websecure
      - traefik.http.routers.thisproxylocal.service=api@internal
    networks:
      - web
    restart: unless-stopped

######################################################################

  gitea-server:
    container_name: gitea
    image: gitea/gitea:latest # 直接装最新版就好了，没啥好选的，随意
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - web
    volumes:
      - ./data/gitea-server/data:/data  # /home/data可以替换成你想要的挂载目录
#      - ./app.ini:/etc/gitea/conf/app.ini
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.gitea-server.rule=Host(`web.yudady.tk`) || Path(`/web`) # replace sr.cloudwatch.net with your domain name, leave /sonarr unchanged for now
#      - traefik.http.routers.gitea-server.entrypoints=websecure
#      - traefik.http.routers.gitea-server.tls.certresolver=letsencrypt
#      - "traefik.http.services.gitea-web-svc.loadbalancer.server.port=3000"

networks:
  web:
    external: true

