apiVersion: v1
kind: Pod
metadata:
  name: myappv1
  labels:
    app: myappv1
    type: demo
spec:
  containers:
    - name: myappv1
      image: yudady/myapp:v1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: myappv2
  labels:
    app: myappv2
    type: demo
spec:
  containers:
    - name: myappv2
      image: yudady/myapp:v2
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    type: demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80