version: '3.9'

services:

  drone-server:
    container_name: drone
    image: 'yudady/drone:2.15.0'
    ports:
      - '8080:80'
      - '8443:443'
    restart: always
    networks:
      - web
    volumes:
      - ./data/drone-server/data:/data'
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GITEA_CLIENT_ID=38c38b5e-29a3-477b-97ae-86c5459f291b
      - DRONE_GITEA_CLIENT_SECRET=gto_xi7grptbacrlxogyi7pa7joox5sut7pbt7le37hk5p4wzdj4zbtq
      - 'DRONE_GITEA_SERVER=http://localhost:3000'
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_RPC_SECRET=74cdedb4e85d3d6458b9624bbeca1c6d
      - 'DRONE_SERVER_HOST=localhost:8080'
      - DRONE_SERVER_PROTO=http


networks:
  web:
    external: true

