apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/yudady/argocd-app-config
    targetRevision: HEAD
    path: dev/k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true