version: "3"

services:
  o12db:
    image: yudady/o12db
    ports:
      - "1521:1521"
      - "8080:8080"
      - "2222:22"
    environment:
      - PASS=oracle
      - WEB_CONSOLE=false
      - DBCA_TOTAL_MEMORY=4096
      - IMPORT_FROM_VOLUME=true
    volumes:
      - ./data:/u01/app/oracle
    container_name: o12db
    restart:
      always

### hostname: localhost
### port: 1521
### sid: xe
### service name: xe
### username: system
### password: oracle

################################################
################################################
################################################
# select userenv('language') from dual;
# TRADITIONAL CHINESE_TAIWAN.AL32UTF8
################################################
################################################
# ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
# CREATE USER core IDENTIFIED BY core;
# GRANT CONNECT TO core;
# GRANT CONNECT, RESOURCE, DBA TO core;
# ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE;

