name: utils
on:
  push:
    branches:
      - main
    paths:
      - 'utils/**'
      - '.github/workflows/build-utils.yml'

jobs:

  utils:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17


      #########################
      #########################
      #########################

      - name: change gradlew Permission
        run: chmod +x ./utils/gradlew

      - name: build gradle jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar
          build-root-directory: ./utils

      #######################################
      ######### maven settings.xml ################
      #######################################

      - name: 創建一個 settings-xml 放在 maven 預設目錄 .m2/settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: >
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/yudady/yudady.github.io",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "yudady",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]

        # output_file: .m2/settings.xml  => Optional String path of to generate settings.xml. By default, ~/.m2/settings.xml is used.



      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: ./utils
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




      #######################################
      ######### slack start ################
      #######################################

      - name: slack report Status
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
          notify_when: "success,failure,cancelled,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}




